# mssql server 2016 developer image
FROM microsoft/windowsservercore

# maintainer for image metadata
MAINTAINER Perry Skountrianos

# set environment variables
ENV sql_server_exe_download_url "https://go.microsoft.com/fwlink/?linkid=829177"

ENV sql_server_box_download_url "https://go.microsoft.com/fwlink/?linkid=829178"

ENV sa_password _
ENV attach_dbs "[]"

# make install files accessible
COPY . /
WORKDIR /

# download sql server box
RUN powershell -Command (New-Object System.Net.WebClient).DownloadFile('%sql_server_box_download_url%', 'SQLServer2016-DEV-x64-ENU.box')

# download and install Microsoft SQL 2014 Express Edition in one step
RUN powershell -Command (New-Object System.Net.WebClient).DownloadFile('%sql_server_exe_download_url%', 'SQLServer2016-DEV-x64-ENU.exe') && /SQLServer2016-DEV-x64-ENU.exe /qs /x:setup && /setup/setup.exe /q /ACTION=Install /INSTANCENAME=SQLDEV /FEATURES=SQLEngine /UPDATEENABLED=0 /SQLSVCACCOUNT="NT AUTHORITY\System" /SQLSYSADMINACCOUNTS="BUILTIN\ADMINISTRATORS" /TCPENABLED=1 /NPENABLED=0 /IACCEPTSQLSERVERLICENSETERMS && del /F /Q SQLServer2016-DEV-x64-ENU.exe && del /F /Q SQLServer2016-DEV-x64-ENU.box && rd /q /s setup

RUN powershell -Command \
        set-strictmode -version latest ; \
        stop-service MSSQL`$SQLDEV ; \
        set-itemproperty -path 'HKLM:\software\microsoft\microsoft sql server\mssql13.SQLDEV\mssqlserver\supersocketnetlib\tcp\ipall' -name tcpdynamicports -value '' ; \
        set-itemproperty -path 'HKLM:\software\microsoft\microsoft sql server\mssql13.SQLDEV\mssqlserver\supersocketnetlib\tcp\ipall' -name tcpport -value 1433 ; \
        set-itemproperty -path 'HKLM:\software\microsoft\microsoft sql server\mssql13.SQLDEV\mssqlserver\' -name LoginMode -value 2 ;

CMD powershell ./start -sa_password %sa_password% -attach_dbs \"%attach_dbs%\" -Verbose
